-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 22:41:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gym_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym_db` DEFAULT CHARACTER SET utf8 ;
USE `gym_db` ;

-- -----------------------------------------------------
-- Table `gym_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_db`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `telefono` VARCHAR(15) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_db`.`Rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_db`.`Rutina` (
  `idRutina` INT NOT NULL AUTO_INCREMENT,
  `nombre_rutina` VARCHAR(45) NULL,
  `nivel` VARCHAR(20) NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idRutina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_db`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_db`.`Ejercicio` (
  `idEjercicio` INT NOT NULL AUTO_INCREMENT,
  `nombre_ejercicio` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idEjercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_db`.`User_has_Rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_db`.`User_has_Rutina` (
  `User_idUser` INT NOT NULL,
  `Rutina_idRutina` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Rutina_idRutina`),
  INDEX `fk_User_has_Rutina_Rutina1_idx` (`Rutina_idRutina` ASC),
  INDEX `fk_User_has_Rutina_User_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_User_has_Rutina_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `gym_db`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Rutina_Rutina1`
    FOREIGN KEY (`Rutina_idRutina`)
    REFERENCES `gym_db`.`Rutina` (`idRutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym_db`.`Rutina_has_Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym_db`.`Rutina_has_Ejercicio` (
  `Rutina_idRutina` INT NOT NULL,
  `Ejercicio_idEjercicio` INT NOT NULL,
  `series` INT NULL,
  `repeticiones` INT NULL,
  `peso` INT NULL,
  PRIMARY KEY (`Rutina_idRutina`, `Ejercicio_idEjercicio`),
  INDEX `fk_Rutina_has_Ejercicio_Ejercicio1_idx` (`Ejercicio_idEjercicio` ASC),
  INDEX `fk_Rutina_has_Ejercicio_Rutina1_idx` (`Rutina_idRutina` ASC),
  CONSTRAINT `fk_Rutina_has_Ejercicio_Rutina1`
    FOREIGN KEY (`Rutina_idRutina`)
    REFERENCES `gym_db`.`Rutina` (`idRutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rutina_has_Ejercicio_Ejercicio1`
    FOREIGN KEY (`Ejercicio_idEjercicio`)
    REFERENCES `gym_db`.`Ejercicio` (`idEjercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
